### ISSUE TITLE
Token needs updating

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/lagranto-feedstock#1]
Appears the token is out-of-date here and needs to be updated. @isuruf, would you be able to look at this? Also is it possible to get a non-`[skip ci] [ci skip]` commit message so that the build can complete. I suppose we could readd through staged-recipes, but defer to your judgement here.

**Comment by isuruf** [comment]
Strange. the appveyor token in `conda-forge.yml` is correct.

**Comment by isuruf** [comment]
It's a sha256 mismatch, not a token issue

**Comment by jakirkham** [comment]
Ah ok. My bad. Sorry for the confusion. Will close this out.
